import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/event.dart';
import '../core/logger.dart';

/// Service for managing audit events (append-only log)
class EventService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  static const String _collectionName = 'events';

  /// Log an event to the audit trail
  Future<void> logEvent({
    required EventType type,
    String? emergencyId,
    String? entityId,
    Map<String, dynamic>? data,
    String? description,
  }) async {
    try {
      final userId = _auth.currentUser?.uid;
      final timestamp = DateTime.now();

      final event = Event(
        id: '', // Will be generated by Firestore
        type: type,
        timestamp: timestamp,
        userId: userId,
        emergencyId: emergencyId,
        entityId: entityId,
        data: data,
        description: description,
      );

      await _firestore.collection(_collectionName).add(event.toFirestore());

      AppLogger.i(
        'Event logged: ${type.toString().split('.').last}',
        {
          'emergencyId': emergencyId,
          'entityId': entityId,
        },
      );
    } catch (e, stackTrace) {
      AppLogger.e('Failed to log event: ${type.toString().split('.').last}', e, stackTrace);
      // Don't throw - event logging should not break the main flow
    }
  }

  /// Get events for a specific emergency
  Stream<List<Event>> getEmergencyEvents(String emergencyId) {
    return _firestore
        .collection(_collectionName)
        .where('emergencyId', isEqualTo: emergencyId)
        .orderBy('timestamp', descending: false)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Event.fromFirestore(doc))
            .toList());
  }

  /// Get all events (for admin/debugging)
  Stream<List<Event>> getAllEvents({int? limit}) {
    var query = _firestore
        .collection(_collectionName)
        .orderBy('timestamp', descending: true);

    if (limit != null) {
      query = query.limit(limit);
    }

    return query.snapshots().map(
          (snapshot) => snapshot.docs.map((doc) => Event.fromFirestore(doc)).toList(),
        );
  }
}

