// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these placeholder values with your actual Firebase configuration values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOfOBSmESry0ZvR2ZXvHD6zMrhSN1DnA',
    appId: '1:855143760278:web:6e5ba9d9744997e0691db7',
    messagingSenderId: '855143760278',
    projectId: 'healyri-af36a',
    authDomain: 'healyri-af36a.firebaseapp.com',
    storageBucket: 'healyri-af36a.firebasestorage.app',
    measurementId: 'G-6PC1138647',
  );

  // You can find these values in the Firebase console under Project settings > Your apps

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVrrCtEUr_ZT0tY6utCfJBllpW6Yv73o',
    appId: '1:855143760278:android:3a350c9a58812102691db7',
    messagingSenderId: '855143760278',
    projectId: 'healyri-af36a',
    storageBucket: 'healyri-af36a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrb3f3s4GGloQmMOLB5Irrkn_taaukNJ0',
    appId: '1:855143760278:ios:e30963a03083e558691db7',
    messagingSenderId: '855143760278',
    projectId: 'healyri-af36a',
    storageBucket: 'healyri-af36a.firebasestorage.app',
    androidClientId: '855143760278-pc3p5o3eq522kcbomdvjt1eg5g6qpv48.apps.googleusercontent.com',
    iosClientId: '855143760278-5jda3jqsabi8otgnbj2bu7op2q8fa49j.apps.googleusercontent.com',
    iosBundleId: 'com.example.healyri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrb3f3s4GGloQmMOLB5Irrkn_taaukNJ0',
    appId: '1:855143760278:ios:e30963a03083e558691db7',
    messagingSenderId: '855143760278',
    projectId: 'healyri-af36a',
    storageBucket: 'healyri-af36a.firebasestorage.app',
    androidClientId: '855143760278-pc3p5o3eq522kcbomdvjt1eg5g6qpv48.apps.googleusercontent.com',
    iosClientId: '855143760278-5jda3jqsabi8otgnbj2bu7op2q8fa49j.apps.googleusercontent.com',
    iosBundleId: 'com.healyri.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkOfOBSmESry0ZvR2ZXvHD6zMrhSN1DnA',
    appId: '1:855143760278:web:7e939184c8eab116691db7',
    messagingSenderId: '855143760278',
    projectId: 'healyri-af36a',
    authDomain: 'healyri-af36a.firebaseapp.com',
    storageBucket: 'healyri-af36a.firebasestorage.app',
    measurementId: 'G-C3EB87LFRG',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'healyri-af36a',
    storageBucket: 'healyri-af36a.appspot.com',
  );
}